### ISSUE TITLE
[node, client, messaging] Use native nats auth

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#820] opened 2020-02-06 19:21 UTC
Old auth was painfully slow. Need to make sure channel auth is using native NATS auth schemes.

**Comment by rhlsthrm** [comment] 2020-02-06 19:34
Things to consider:

When the node locks for a client, it locks either on a multisig address, an app instance ID, or [add other lock names here]. The client auth needs to be tied to their xpub somehow so that we can verify only the identified user is able to lock their channel. If it's an app instance ID lock, the app will have to be traced back to the channel and still verified to the user.

**Comment by ArjunBhuptani** [comment] 2020-02-24 10:41
This one is a duplicate of https://github.com/ConnextProject/indra/issues/325, going to close this and then bump the other one in priority + add it to this sprint

**Closed by ArjunBhuptani** 2020-02-24 10:41 UTC
Labels: Bug, p1: Time Sensitive
