### ISSUE TITLE
[card] Recipient coming back online with pending async transfers seems to break

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#444] opened 2019-10-18 16:27 UTC
**To Reproduce**
1. Receive transfer when offline
2. Come online to retrieve the transfer

**Comment by LayneHaber** [comment] 2019-10-18 18:52
Can't reproduce, tried:
- single awaiting async payment
- multiple awaiting async payments
- large value (recipient undercollateralized) async payment

**Comment by ArjunBhuptani** [comment] 2019-10-18 21:45
Not able to reproduce this on staging either - closing

**Closed by ArjunBhuptani** 2019-10-18 21:45 UTC
Labels: p1: Time Sensitive
