### ISSUE TITLE
Double sends to offline recipient sometimes

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#576] opened 2019-11-23 09:52 UTC
**Describe the bug**
Sometimes I see that the client sends multiple times to the node. The recipient only receives one of the transfers though, which is very bad.

**To Reproduce**
1. Send to offline recipient

**Expected behavior**
Only send once.

**Comment by rhlsthrm** [comment] 2019-11-23 11:19
This only happens sometimes, trying to figure out if it's related to double sending of propose messages.

**Comment by LayneHaber** [comment] 2019-11-25 05:58
Could it be because the events for propose and install are the same and it's being handled twice on the client side/ believe this was fixed at the cf level in #577 and at the client level in #559

**Comment by rhlsthrm** [comment] 2019-11-25 07:27
OK, will wait for the fixes on the other branches.

**Comment by ArjunBhuptani** [comment] 2019-11-29 20:05
@rhlsthrm have you been able to repro this again now that fixes are merged? If not, we should close this

**Comment by ArjunBhuptani** [comment] 2019-11-29 22:26
Closing for now since no one can reproduce this, we can reopen this if needed.

**Closed by ArjunBhuptani** 2019-11-29 22:26 UTC
Labels: More Info Needed, p0: Drop Everything
